- name: Setup and enable webservers on all hosts
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install the latest version of Apache for RHEL/CentOS
      ansible.builtin.yum:
        name: httpd
        state: latest
      when: 
        - ansible_facts['os_family'] == "RedHat"

    - name: Install the latest version of Apache for Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      when: 
        - ansible_facts['os_family'] == "Debian" 

    - name: Start service httpd, if not started for RHEL/CentOS
      ansible.builtin.service:
        name: httpd
        state: started
      when:
        - ansible_facts['os_family'] == "RedHat"

    - name: Start service apache2, if not started for Ubuntu
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: Enable service httpd for RHEL/CentOS
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
      when:
        - ansible_facts['os_family'] == "RedHat"

    - name: Enable service apache2 for Ubuntu
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: Enable service firewalld for RHEL
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started
      when:
        - ansible_facts['os_family'] == "RedHat"

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
      when:
        - ansible_facts['os_family'] == "RedHat"

    - name: permit traffic in default zone for https service
      ansible.posix.firewalld:
        service: https
        permanent: true
        immediate: true
        state: enabled
      when:
        - ansible_facts['os_family'] == "RedHat"

