- name: Remove all webserver configs
  hosts: all
  gather_facts: true
  tasks:

    - name: Uninstall IIS
      ansible.windows.win_feature:
        name:
        - Web-Server
        - Web-Common-Http
        state: absent
        include_sub_features: true
        include_management_tools: true

#    - name: Stop IIS
#      ansible.windows.win_service:
#        name: W3Svc
#        state: stopped
