- name: Create a webserver
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Remove Apache for RHEL/CentOS
      ansible.builtin.dnf:
        name: httpd
        state: absent
      when: 
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution'] == "CentOS"

    - name: Remove Apache for Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: absent
      when: 
        - ansible_facts['distribution'] == "Ubuntu"
