- name: Setup and enable webservers on all hosts
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install the latest version of Apache for RHEL/CentOS
      ansible.builtin.dnf:
        name: httpd
        state: latest
      when: 
        - ansible_facts['os_family'] == "RedHat"

    - name: Install the latest version of Apache for Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      when: 
        - ansible_facts['os_family'] == "Debian" 

    - name: Start service httpd, if not started for RHEL/CentOS
      ansible.builtin.service:
        name: httpd
        state: started
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution == "CentOS"

    - name: Start service apache2, if not started for Ubuntu
      ansible.builtin.service:
        name: apache2
        state: started
      when:
        - ansible_distribution == "Ubuntu"

    - name: Enable service httpd for RHEL/CentOS
      ansible.builtin.service:
        name: httpd
        enabled: yes
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution == "CentOS"

    - name: Enable service apache2 for Ubuntu
      ansible.builtin.service:
        name: apache2
        enabled: yes
      when:
        - ansible_distribution == "Ubuntu"




