- name: Create a webserver
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install the latest version of Apache for RHEL/CentOS
      ansible.builtin.dnf:
        name: httpd
        state: latest
      when: 
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution'] == "CentOS"

    - name: Install the latest version of Apache for Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      when: 
        - ansible_facts['distribution'] == "Ubuntu"

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: httpd
        enabled: yes
