- name: Remove all webserver configs
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Remove Apache for RHEL/CentOS
      ansible.builtin.yum:
        name: httpd
        state: absent
        autoremove: yes
      when: 
        - ansible_facts['os_family'] == "RedHat"

    - name: Remove Apache for Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: absent
        autoremove: yes
      when: 
        - ansible_facts['os_family'] == "Debian"

    - name: block traffic in default zone for http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled
      when:
        - ansible_facts['os_family'] == "RedHat"

    - name: block traffic in default zone for https service
      ansible.posix.firewalld:
        service: https
        permanent: true
        immediate: true
        state: disabled
      when:
        - ansible_facts['os_family'] == "RedHat"
