- name: Setup and enable webservers on all hosts
  hosts: all
  gather_facts: true
  tasks:

    - name: Start IIS
      win_service:
        name: W3Svc
        state: stopped

    - name: Install IIS
      win_feature:
        name:
        - Web-Server
        - Web-Common-Http
        state: absent
        include_sub_features: true
        include_management_tools: true

