- name: Remove all webserver configs
  hosts: all
  gather_facts: true
  tasks:

    - name: Stop IIS
      win_service:
        name: W3Svc
        state: stopped

    - name: Uninstall IIS
      win_feature:
        name:
        - Web-Server
        - Web-Common-Http
        state: absent
        include_sub_features: true
        include_management_tools: true

