- name: Setup and enable webservers on all hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Install IIS
      ansible.windows.win_feature:
        name:
        - Web-Server
        - Web-Common-Http
        state: present
        include_sub_features: true
        include_management_tools: true

    - name: Set service startup mode to auto and ensure it is started
      ansible.windows.win_service:
        name: W3Svc
        start_mode: auto
        state: started
